data_config: '/home/kunhan/workspace/projects/SegTransformer/config/data/NO1_thorax.yaml'

start_channel: 32
deep_supervision: false

lr: 0.0001
n_epoch: 500
step_size: 50
weight_decay: 0.1
loss:
  attention_loss_weight: [1, 1, 1, 1, 1]
  dice_loss_weight: 1

write_summary_loss_batch_step: 100
write_summary_2d_batch_step: 200

logging_epoch_step: 1
val_model_epoch_step: 2
logging_dir: '/home/kunhan/workspace/projects/SegTransformer/log/GSegTrans/segtransformer/v2'
ckpt_dir: '/home/kunhan/workspace/projects/SegTransformer/ckpt/GSegTrans/segtransformer/v2'

load_checkpoint: false

load_checkpoint_encoder: false
freeze_encoder: false
unfreeze_encoder_epoch: null

load_checkpoint_decoder: false
freeze_decoder: false
unfreeze_decoder_epoch: null

ckpt_fn: null
